version: '3'
services:
  db:
    image: postgres:14
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beeldzorg
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: "always"
    ports:
      - 5051:8080
